In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)
c = np.array([[(1.5,2,3),(4,5,6)],
             [(3,1,1),(4,5,6)]], dtype = float)

In [8]:
a , b , c

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],
 
        [[3. , 1. , 1. ],
         [4. , 5. , 6. ]]]))

In [10]:
#array with (3,4) shape all elements are zero
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
#array with (2,3,4) shape all elements are one
np.ones((2,3,4) ,  dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [24]:
# np.arange (start , stop , space) 
d = np.arange(10,25,5)
print(d)

[10 15 20]


In [27]:
# np.linspace(start , stop , number of values between start and stop)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
# np.full(shape , number) fully fills the array with given number
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [11]:
# np.eye(number) gives np.ones array with number * number shape given
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#import random module
import random

In [22]:
# np.random.random(shape) gives array with random values >= 0 and < 1
np.random.random((2,2))

array([[0.23057634, 0.38917397],
       [0.22586297, 0.29759718]])

In [33]:
#This function is used to create an array without initializing the entries of given shape and type.
np.empty((3,1))

array([[1.34322370e-311],
       [0.00000000e+000],
       [1.60216182e-306]])

In [35]:
# gives shape of array
a.shape

(3,)

In [43]:
len(a) , a.shape

(3, (3,))

In [44]:
len(b) , b.shape

(2, (2, 3))

In [45]:
len(c) , c.shape

(2, (2, 2, 3))

In [52]:
# the number of elements(array) in an array
len(np. empty((7,5, 3,15)))

7

In [54]:
# returns number of dimensions of array
b.ndim , c.ndim , a.ndim

(2, 3, 1)

In [58]:
# number of values in array
a.size , b.size , c.size


(3, 6, 12)

In [60]:
# returns data type of elements in array
a.dtype , b.dtype , c.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [63]:
# returns name of data type of elements in array
a.dtype.name , b.dtype.name , c.dtype.name

('int32', 'float64', 'float64')

In [67]:
# changes data type of values in array
a.astype(str) , b.astype(int) , c.astype(float)

(array(['1', '2', '3'], dtype='<U11'),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],
 
        [[3. , 1. , 1. ],
         [4. , 5. , 6. ]]]))

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)
c = np.array([[(1.5,2,3),(4,5,6)],
             [(3,1,1),(4,5,6)]], dtype = float)

In [ ]:
#Array mathematics

In [69]:
a+b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [70]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [71]:
a-b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [75]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [76]:
a**2

array([1, 4, 9], dtype=int32)

In [81]:
np.power(a,9)

array([    1,   512, 19683], dtype=int32)

In [82]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [83]:
a = (np.exp(a))

In [84]:
a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [85]:
tuple(a)

(2.718281828459045, 7.38905609893065, 20.085536923187668)

In [86]:
set(a)

{2.718281828459045, 7.38905609893065, 20.085536923187668}

In [87]:
np.array(a , dtype = int)

array([ 2,  7, 20])

In [88]:
str(a)

'[ 2.71828183  7.3890561  20.08553692]'

In [89]:
np.array(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [94]:
np.log(b)

array([[0.40546511, 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [122]:
lst = [np.sin(a) , np.sin(b) , np.sin(c)]
print(lst)
tuple(lst)
new = np.array(lst)
print(new)

[array([0.41078129, 0.89385495, 0.94447101]), array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]]), array([[[ 0.99749499,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ]],

       [[ 0.14112001,  0.84147098,  0.84147098],
        [-0.7568025 , -0.95892427, -0.2794155 ]]])]
[array([0.41078129, 0.89385495, 0.94447101])
 array([[ 0.99749499,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ]])
 array([[[ 0.99749499,  0.90929743,  0.14112001],
         [-0.7568025 , -0.95892427, -0.2794155 ]],

        [[ 0.14112001,  0.84147098,  0.84147098],
         [-0.7568025 , -0.95892427, -0.2794155 ]]])]


<ipython-input-122-6fe7d02264d5>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  new = np.array(lst)


In [109]:
np.cos(a) , np.cos(b) , np.cos(c)

(array([-0.91173391,  0.44835624,  0.32859476]),
 array([[ 0.0707372 , -0.41614684, -0.9899925 ],
        [-0.65364362,  0.28366219,  0.96017029]]),
 array([[[ 0.0707372 , -0.41614684, -0.9899925 ],
         [-0.65364362,  0.28366219,  0.96017029]],
 
        [[-0.9899925 ,  0.54030231,  0.54030231],
         [-0.65364362,  0.28366219,  0.96017029]]]))

In [123]:
np.log(a) , np.log(b) , np.log(c)

(array([1., 2., 3.]),
 array([[0.40546511, 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]]),
 array([[[0.40546511, 0.69314718, 1.09861229],
         [1.38629436, 1.60943791, 1.79175947]],
 
        [[1.09861229, 0.        , 0.        ],
         [1.38629436, 1.60943791, 1.79175947]]]))

In [124]:
np.sqrt(a) , np.sqrt(b) , np.sqrt(c)

(array([1.64872127, 2.71828183, 4.48168907]),
 array([[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]),
 array([[[1.22474487, 1.41421356, 1.73205081],
         [2.        , 2.23606798, 2.44948974]],
 
        [[1.73205081, 1.        , 1.        ],
         [2.        , 2.23606798, 2.44948974]]]))

In [125]:
e = np.full((2,2), 7)

In [126]:
e

array([[7, 7],
       [7, 7]])

In [127]:
f = np.eye(2)

In [128]:
f

array([[1., 0.],
       [0., 1.]])

In [129]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [131]:
a.sum() , b.sum() , c.sum()

(30.19287485057736, 21.5, 41.5)

In [132]:
a.min() , b.min() , c.min()

(2.718281828459045, 1.5, 1.0)

In [133]:
a.max() , b.max() , c.max()

(20.085536923187668, 6.0, 6.0)

In [6]:
b.max(axis = 1) , c.max(axis = 1)

(array([3., 6.]),
 array([[4., 5., 6.],
        [4., 5., 6.]]))

In [8]:
b.min(axis = 0 ) , c.min(axis = 0)

(array([1.5, 2. , 3. ]),
 array([[1.5, 1. , 1. ],
        [4. , 5. , 6. ]]))

In [11]:
b.cumsum() , b.cumsum(axis = 1) , b.cumsum(axis = 0)

(array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5]),
 array([[ 1.5,  3.5,  6.5],
        [ 4. ,  9. , 15. ]]),
 array([[1.5, 2. , 3. ],
        [5.5, 7. , 9. ]]))

In [12]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
a.mean() , np.median(a) , np.mean(a) 

(2.0, 2.0, 2.0)

In [32]:
tp = (np.mean(b) , np.median(b) ,  np.mean(c) , np.median(c))
tp

(3.5833333333333335, 3.5, 3.4583333333333335, 3.5)

In [38]:
np.corrcoef(b)

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

In [39]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [42]:
np.var(a) ,a.var()

(0.6666666666666666, 0.6666666666666666)

In [46]:
# varaince
b.var() , np.var(b) , np.var(c) , c.var()

(2.534722222222222, 2.534722222222222, 3.0607638888888893, 3.0607638888888893)

In [51]:
#standard deviation
a.std() , np.std(a) , b.std() , np.std(b) , c.std() , np.std(c)

(0.816496580927726,
 0.816496580927726,
 1.5920810978785667,
 1.5920810978785667,
 1.7495038979347515,
 1.7495038979347515)

In [53]:
# create a view
h = a.view()
h


array([1, 2, 3])

In [57]:
id(h)

3059674678832

In [58]:
id(a)

3059674503952

In [59]:
#deep copy
h = a.copy()

In [60]:
id(h) , id(a)

(3059674680080, 3059674503952)

In [61]:
g = np.copy(a)

In [62]:
g

array([1, 2, 3])

In [63]:
id(g)

3059674677584

In [66]:
#shallow copy
d = a
id(d) , id(a)

(3059674503952, 3059674503952)

In [69]:
a.sort(),a

(None, array([1, 2, 3]))

In [71]:
c.sort(axis=0)
c

array([[[1.5, 1. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [74]:
# transpose
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [75]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [76]:
# changing shape
# .ravel() convert mulidimensional array to one dimension array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [78]:
g = c.ravel()

In [81]:
g.reshape(3,4)

array([[1.5, 1. , 1. , 4. ],
       [5. , 6. , 3. , 2. ],
       [3. , 4. , 5. , 6. ]])

In [87]:
h.resize((2,6))
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [88]:
np.append(h, g)

array([1. , 2. , 3. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.5,
       1. , 1. , 4. , 5. , 6. , 3. , 2. , 3. , 4. , 5. , 6. ])

In [89]:
np.insert(a, 1,5)

array([1, 5, 2, 3])

In [91]:
np.insert(b, 2 , 5)

array([1.5, 2. , 5. , 3. , 4. , 5. , 6. ])

In [92]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [93]:
np.delete(a, [1])

array([1, 3])

In [94]:
a

array([1, 2, 3])

In [97]:
np.delete(a , [2])

array([1, 2])

In [100]:
 h = a

In [101]:
np.concatenate((a,h) , axis = 0)

array([1, 2, 3, 1, 2, 3])

In [102]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [106]:
e = np.full((2,2) , 7)
e


array([[7, 7],
       [7, 7]])

In [110]:
f= np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [111]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [112]:
np.hsplit(a, 3)

[array([1]), array([2]), array([3])]

In [119]:
tp = tuple(np.vsplit(b,2))

In [116]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [122]:
type(tp)

tuple

In [123]:
list(tp)

[array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])]

In [6]:
a[a<2]

array([1])